name: Unit Test and Lint

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yaml"
      - "scaffold/data/**"
      - "**/testdata/**"

  pull_request:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yaml"
      - "scaffold/data/**"
      - "**/testdata/**"

  workflow_dispatch:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.24.1"
      
      - name: Display Go version
        run: go version

      - name: Run unit test
        run: go test ./...

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: "v2.2.1"
